image: docker:latest

stages:
  - builds
  - test
  - release
  - deploy

variables:
  IMAGE: $DOCKER_USER/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
  RELEASE: $DOCKER_USER/$CI_PROJECT_NAME:latest

before_script:
   - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

build:
  stage: builds
  tags:
    - shared_runner
  script:
   - cd app && docker build --pull -t $IMAGE .
   - docker push $IMAGE

release:
  stage: release
  tags:
    - shared_runner
  script:
    - docker pull $IMAGE
    - docker tag $IMAGE $RELEASE
    - docker push $RELEASE
  only:
    - master

deploy:
  stage: deploy
  before_script: 
    - apk add --no-cache curl
    - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
  tags:
    - shared_runner
  script:
    - ./kubectl config set-cluster local --server=$KUBE_URL --insecure-skip-tls-verify=true
    - ./kubectl config set-credentials gitlab-admin --token=$KUBE_TOKEN
    - ./kubectl config set-context default --cluster=local --user=gitlab-admin
    - ./kubectl config use-context default
#    - ./kubectl config view
#    - ./kubectl get nodes
    - ./kubectl create secret docker-registry myprivateregistry --docker-server=$REGISTRY_URL --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASSWORD --dry-run=client -o yaml | ./kubectl apply -f -
    - ./kubectl apply -f manifests/deployment.yaml
#    - ./kubectl apply -f manifests/service.yaml
    - ./kubectl rollout restart deployment
