apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      run: myapp
  template:
    metadata:
      labels:
        run: myapp
    spec:
      containers:
      - name: myapp
        image: zamanbek/k8s-conf-demo:latest
        imagePullPolicy: Always
        env:
        - name: HTTP_PORT
          value: "8081"
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: myprivateregistry
